### ISSUE TITLE
Wire.requestFrom() should not be followed by Wire.endTransmission()

### ISSUE THREAD

**Issue by Koepel** [Sensirion/arduino-liquid-flow-snippets#1]
The Wire.endTransmission() is only used when **writing** data. It should not be used after the Wire.requestFrom().

The Wire.requestFrom() is a complete I2C transaction on its own. It does the start, sending the i2c address, reading of the data bytes and the stop.

At this moment a Wire.endTransmission() without Wire.beginTransmission (for the Wire library for AVR chip) sends out an i2c address and reads the acknowledge by the sensor. This results into an unnecessary I2C transaction on the bus. It could result in an error when the Wire library is changed and it could be bad with implementations of the Wire library for other processors.

To check if the Wire.requestFrom() is successful, the return value could be checked or a Wire.available() could be called directly after it. The number of received bytes should be the same as the number of requested bytes.

The problem is in these files:
example_01_simple_measurement.ino (once)
example_02_set_resolution.ino (twice)
example_03_read_scalefactor_and_unit.ino (three times)
example_04_read_product_details.ino (just once, only at the bottom in the loop function)
example_05_crc_checksum.ino (once)
example_10_calibration_field.ino (twice)
example_11_read_temperature_voltage.ino (once)
example_12_twos_complement.ino (once)
example_13_DIY_flow_meter.ino (three times)

**Comment by abrauchli** [comment]
Hi @Koepel thanks for the report and apologies for not reacting earlier. We'll fix it shortly.

**Comment by abrauchli** [comment]
Fixed, thanks again.

**Comment by Koepel** [comment]
Thanks, I have checked all the files and as far as I can tell it is okay.

Testing for `if (Wire.available() < 9) {` is the same as `if (Wire.available() != 9) {`. You can use both. Some think that more bytes can be received, but that is not possible, since the Master determines how many bytes will be read during a Wire.requestFrom(). Therefor using `if (Wire.available() < 9) {` is 100% correct.

I noticed one thing though. In the file https://github.com/Sensirion/arduino-liquid-flow-snippets/blob/master/README.md the explanation of the functions of the Wire library might be confusing. It depends on Wire library for a platform/processor what the functions do. In the AVR Wire library, the Wire.endTransmission() does not stop the transmission, it does a start, send address, send data from buffer, and a stop. The Wire.read() reads data from a buffer, not from the bus.

**Comment by abrauchli** [comment]
Right, I tried to clarify it.
