### ISSUE TITLE
SLF3S-1300F Liquid flow sensor I2C via arduino uno provides no useable ic2 signal using snippets

### ISSUE THREAD

**Issue by dandelion-cmd** [Sensirion/arduino-liquid-flow-snippets#3]
Dear Sensirion
 
Purpose of the project: choice of sensor  for a sub project in liquid handling. To to verify if SLF3S sensor ic2 data can be handled, displayed and written -as pilot project before scaling up with multiple sensors per device that will be i2c multiplexed to provide values used for PID controlled feedback loops.

Purpose of this inquiry: to  obtain either a working code for proof that Arduino Uno, any other type, can handle the sensor derived I2C data flow temp and flags or a suggestion to abandon i2c devices. Any help is valued, any costs assosciated with this inquiry may be invoiced. 

THANK YOU VERY MUCH

Materials: Arduino uno, 3.3v, no additional pullups, wired as datasheet-instructed, cable length appros 20 cm. SLF3S-1300F sensor evaluation kit. 

Description of the problem: No matter how the address of the sensor is modified, the above mentioned and below provided code keeps outputting: "Error while sending soft reset command, retrying..." on the serial monitor. 
The sensor could NOT be detected by several different 12c scanners (scanning for 7 bit).
The sensor is working FINEwith the provided RS485-USB cable using the viewer software.
3.3V OP verified
Oscilloscope reading of SCL and SCL during serial monitor updates the serial monitor error : periodically (pulled down from 2v to 0V
![grafik](https://user-images.githubusercontent.com/65943416/82876489-27542680-9f39-11ea-83ad-3e01a4928f06.png)

all Sensirion-provided codes were tried out (with modified sensor addresses from 4 to 8) and include: 
```cpp
/*
 * Copyright (c) 2018, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*******************************************************************************
 * Purpose:  Example code for the I2C communication with Sensirion Liquid
 *           Flow Sensors
 *
 *           Read measurements from the sensor
 ******************************************************************************/

#include <Wire.h> // Arduino library for I2C

const int ADDRESS = 0x80; // Standard address for Liquid Flow Sensors

// -----------------------------------------------------------------------------
// Arduino setup routine, just runs once:
// -----------------------------------------------------------------------------
void setup() {
  int ret;

  Serial.begin(9600); // initialize serial communication
  Wire.begin();       // join i2c bus (address optional for master)

  do {
    // Soft reset the sensor
    Wire.beginTransmission(ADDRESS);
    Wire.write(0xFE);
    ret = Wire.endTransmission();
    if (ret != 0) {
      Serial.println("Error while sending soft reset command, retrying...");
    }
  } while (ret != 0);

  delay(50); // wait long enough for chip reset to complete
}

// -----------------------------------------------------------------------------
// The Arduino loop routine runs over and over again forever:
// -----------------------------------------------------------------------------
void loop() {
  int ret;
  uint16_t raw_sensor_value;
  int16_t signed_sensor_value;

  // To perform a measurement, first send 0xF1 to switch to measurement mode,
  // then read 2 bytes + 1 CRC byte from the sensor.
  Wire.beginTransmission(ADDRESS);
  Wire.write(0xF1);
  ret = Wire.endTransmission();
  if (ret != 0) {
    Serial.println("Error during write measurement mode command");

  } else {
    Wire.requestFrom(ADDRESS, 2);       // reading 2 bytes ignores the CRC byte
    if (Wire.available() < 2) {
      Serial.println("Error while reading flow measurement");

    } else {
      raw_sensor_value  = Wire.read() << 8; // read the MSB from the sensor
      raw_sensor_value |= Wire.read();      // read the LSB from the sensor

      Serial.print("raw value from sensor: ");
      Serial.print(raw_sensor_value);

      signed_sensor_value = (int16_t) raw_sensor_value;
      Serial.print(", signed value: ");
      Serial.println(signed_sensor_value);
    }
  }

  delay(1000); // milliseconds delay between reads (for demo purposes)
}
```

**Comment by rnestler** [comment]
> to obtain either a working code for proof that Arduino Uno

The Arduino Uno runs with 5V right? So it may need level shifters (https://www.adafruit.com/product/757) for the I2C communication to work.

The SLF3S-1300F needs a supply voltage between 3.2V and 3.8V, so powering it with 3.3V is fine.

> no additional pullups,

Are there existing I2C pullups on the Arduino Uno? If yes, when they pull up to 5V this may damage the SLF3S-1300F since the input voltages on SCL and SDA would be higher than its supply voltage.

>  Oscilloscope reading of SCL and SCL during serial monitor updates the serial monitor error : periodically (pulled down from 2v to 0V

From this it seems to me that there are no I2C pull up resistors. So if there really are no existing pull-ups on the Arduino Uno, consider adding pull-up resistors to 3.3V, which *may* work for communication with the Arduino Uno, since 3.3V is above the logic threshold of 2.5V which is to be expected of a 5V powered device.

Hope that helps :slightly_smiling_face:

**Comment by rnestler** [comment]
Btw. from your oscilloscope screenshot I guess you speak German, right? Feel free to respond in German if that is easier for you, I'm from the German speaking part of Switzerland so it is my native language :slightly_smiling_face:

**Comment by dandelion-cmd** [comment]
Lieber Herr N.

Danke wirklich vielmals für die Interpretation und Hilfestellung zur 
Hardware.

War irgendwie der Meinung, die pullupRs sollten schon installiert sein, 
aber offenbar nicht, (zum Glück in diesem Fall) . Bestellte 
levelshifters sollten schon lange angekommen sein, sobald da baue ich 
entsprechend auf. Zwischenzeitlich versuche ich mit pullup nach 3.3v mit 
hilfe von Rs und lasse Sie den Fortschritt wissen.

Mit den besten Grüssen, bleiben Sie gesund

Daniel




Am 27.05.2020 um 11:14 schrieb Raphael Nestler:
